name: CI - Cloud IAC Scanner

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  iac-scanner:
    name: Cloud IAC Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cloud IAC parser
        uses: sysdiglabs/cloud-iac-scanner-action@v0.0.6
        with:
          parser: 'terraform'